### ISSUE TITLE
Can users add their vocabulary set in any config file?

### ISSUE THREAD

**Issue by fyang93** [sedm0784/vim-you-autocorrect#2]
First, thank you for the brilliant vim plugin!
However, I still wonder if there is any future plan about adding a config file to customize vocabulary set.
For example, I found some tech terms are not supported well, like `pretrained model`. And in your demo, `no brainer` is corrected to `no briner` which is also a wrong correction. I guess these problems can be solved by a customized thesaurus. How do you like?

**Comment by sedm0784** [comment]
> First, thank you for the brilliant vim plugin!

I'm glad you like it!

Keep your eyes peeled for version 1.1, coming soon to a GitHub near you.

> I still wonder if there is any future plan about adding a config file to customize vocabulary set.

All this plugin does is accept Vim's first suggested spelling for each word, so you can use Vim's standard commands for altering the wordlist. See `:help 'spell'` for details on Vim's spell-checking feature, and specifically, `:help zg`.

> in your demo, `no brainer` is corrected to `no briner`.

Yes, yes it is.

**Comment by fyang93** [comment]
Thank you for the reply and suggestions.
I used `set spell` but never know `zg` shortcut, TIL!
I'm looking forward to the version 1.1, good luck
