### ISSUE TITLE
does not work?

### ISSUE THREAD

**Issue by alex-popov-tech** [sedm0784/vim-you-autocorrect#4]
when I enable plugin with command from README I can see that spelling it turned ON, but after typing some words i can see that any suggestions applied :(
Here is my config - https://github.com/alex-popov-tech/.dotfiles/blob/master/nvim/plugins.vim#L385

**Comment by sedm0784** [comment]
Sorry it's not working for you. I'm sure we can figure out what's going, though!

Could you please try:

1. Commenting out the other `Plug` lines from your config, to check that another plugin is not interfering with Vim You, Autocorrect!,

2. Try running the command `verbose au vim_you_autocorrect` *after* running `:EnableAutocorrect` and paste the output in here.

**Comment by alex-popov-tech** [comment]
It's working now, after disabling all the other plugins! Thanks!
I will figure out what's wrong here...

**Comment by sedm0784** [comment]
Great! Thanks for letting me know.

If you let me know which other plugin was causing the issue, I'll take a look and see if I can figure out what was going wrong and whether there's any way the two can play nicely together.

**Comment by alex-popov-tech** [comment]
Yeah, trying to figure out...Just a quick question - how do you handle cases when vim should not fix your word? F.e. `numberify` or `aws` ?

**Comment by sedm0784** [comment]
You can teach Vim about a spelling by placing your cursor on the word and pressing [`zg`](https://vimhelp.org/spell.txt.html#zg) to add it to your spellfile (which is persistent) or [`zG`](https://vimhelp.org/spell.txt.html#zG) to add it to your internal wordlist, (which will be lost when you quit Vim).

If you wanted a mapping to teach Vim about a spelling _after_ Vim You, Autocorrect! has corrected it, you could use something like:

    nmap <Leader>zG <Plug>VimyouautocorrectJump<Plug>VimyouautocorrectUndozG

**Comment by sedm0784** [comment]
@alex-popov-tech Hello! Just wondering if you ever figured out which of your other plugins was INTERFERING with Vim You, Autocorrect!?

**Comment by alex-popov-tech** [comment]
Hey @sedm0784 !
Thanks for reaching out!
I've updated since last comment my config like 100+ times :D
anyways, enabled your plugin now, and it works nice with all my plugins, thanks for that plugin!

**Comment by sedm0784** [comment]
Haha yes it was a while ago :)

Glad Vim You, Autocorrect! is working well for you now. Please do open new issues if you have any other problems/feature requests.
