### ISSUE TITLE
`im` != `if`

### ISSUE THREAD

**Issue by usmcamp0811** [sedm0784/vim-you-autocorrect#6]
Cool plugin.. just installed it and it works but is a little quirky.. I am finding that it doesn't like `im`. I would expect it to auto-fix it to `I'm` but its changing it to `if`. How would I go about correcting this behavior? I tried adding `I'm` to my spell vocabulary with `zg` but that didn't seem to fix it.

**Comment by sedm0784** [comment]
I'm very sorry for not responding sooner. I didn't see this issue until just now.

> Cool plugin

Thanks!

> it [...] is a little quirky

Indeed.

I'm afraid you will have to [take up issues with Vim's `'spell'` corrections with Bram](https://github.com/vim/vim/issues). In the meantime, you should be able to work around this issue by adding the following abbreviation to your vimrc:

    iabbrev im I'm

See [:help 24.7](https://vimhelp.org/usr_24.txt.html#24.7) for more info on how this works.

Let me know if this helps!
