### ISSUE TITLE
[Question] vim you autocorrect detects spelling mistake when first letter of new sentence is not capitalized but does not correct it

### ISSUE THREAD

**Issue by damienlancry** [sedm0784/vim-you-autocorrect#7]
Hello, 

First thing first: this is a great plugin!
Second, my issue is: when I type I usually do not bother pressing shift except for punctuation. 
Therefore, I usually do not bother capitalizing the first letter of my sentences. 
It seems the plugin detects it as a spelling error since it is underlined but does not autocorrect. 
If I do "[s" and then "1z=" it correctly corrects it by capitalizing the first letter. I read on [Reddit](https://www.reddit.com/r/vim/comments/8azuun/comment/dx38nbb/?utm_source=share&utm_medium=web2x&context=3) that it is what this plugin does in a nutshell. 
- then why does it not work in this case? 
- is it a bug or a feature? 
- if it is a feature, how to enable auto-capitalization of the first letter of a sentence? 
- if it is a bug, can we fix it? (I could contribute with some guidance, I am new to vimscript)

I know there must be some other plugins I can add to my vimrc to do that, but I thought this plugin should be able to handle that and I would prefer killing two birds with one stone.

Thanks in advance!

**Comment by sedm0784** [comment]
It's a bug! Thanks for reporting it. I will fix.

**Comment by sedm0784** [comment]
I've now pushed a fix for this.

Please do let me know if this doesn't fix the issue for you, or if it introduces any new problems. Thanks again for reporting it!

Note also that capitalisation errors at the start of a line are still not corrected, but they are also missed by `[s`. I opened an issue for this on the main vim repo: vim/vim#10838.
